### ISSUE TITLE
Support the poll functions

### ISSUE THREAD

**Issue by lu-zero** [nthieu173/srt-rs#1]
The -sys bindings do not expose the polling functions and they would be nice to have to implement asynchronous read/write abstractions.

**Comment by nthieu173** [comment]
You are right, I just haven't gotten around to doing it yet because there were still many bugs with just the synchronous portion of the code. However, I've recently seems to have squashed them so I will soon get around to doing this.

**Comment by lu-zero** [comment]
I can send you a patchset, I prepared the bindgen bindings meanwhile.

**Comment by lu-zero** [comment]
https://github.com/lu-zero/async-srt-rs/tree/master/srt-sys here is what I worked on. I ported over the example code to make sure the bindings are behaving correctly.

**Comment by nthieu173** [comment]
Thanks to looking at your repo, I've switched over to bindgen and exposed all of the poll functions. It hasn't been Rustified though and not exposed through the general library yet.

**Comment by nthieu173** [comment]
@lu-zero I have implemented an async rust layer over the epoll functions, pull requests to improve it would be welcome but I think this issue can be closed.

**Comment by lu-zero** [comment]
Thank you a lot! I'll try it soon :)
