### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by lu-zero** [nthieu173/srt-rs#5]
Right now building on macOS would fail, ideally it should be a matter of using `os_sockaddr` instead of the hand-crafted conversion plus using `target_family="unix"` to import the right linger struct.

**Comment by nthieu173** [comment]
Looks good, thanks! I never found this crate, else it would have helped SO MUCH. I had so many problem with endianness.

**Comment by lu-zero** [comment]
I'm glad of being of help :)
